# Generated by Django 4.2.6 on 2024-09-21 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_advocate_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-filing_date']},
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='case',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='case',
            name='user',
        ),
        migrations.AddField(
            model_name='advocate',
            name='address',
            field=models.TextField(blank=True, default='address not provided', null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='bar_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='advocate',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='firm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='license_issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advocate',
            name='phone_number',
            field=models.CharField(blank=True, default='0000000', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='specialty',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='advocate',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='court_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cases', to='myapp.customuser'),
        ),
        migrations.AddField(
            model_name='case',
            name='filing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='case',
            name='litigant',
            field=models.ForeignKey(default='unknown litigant', on_delete=django.db.models.deletion.CASCADE, related_name='litigant_cases', to='myapp.customuser'),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default='law', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
        migrations.AlterField(
            model_name='case',
            name='advocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advocate_cases', to='myapp.customuser'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('litigant', 'Litigant'), ('advocate', 'Advocate'), ('staff', 'Court Staff')], max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('litigant', 'Litigant'), ('advocate', 'Advocate'), ('staff', 'Court Staff')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
